# 자동 리뷰어 등록 설정
addReviewers: true

# 담당자는 생성자(author)로 자동 등록
addAssignees: author

# 리뷰어 명단
reviewers:
  - chaeeun037
  - HanCheo
  - jonghopark95
  - peanut-lover

# 최소 리뷰어 등록 수
# default: 0 => 명단에 있는 모든 리뷰어 등록
numberOfReviewers: 0
